[target.armv7-unknown-linux-gnueabihf]
image = "sigmaris/avcontrolbuilder:armv7-unknown-linux-gnueabihf"

[target.aarch64-unknown-linux-gnu]
image = "sigmaris/avcontrolbuilder:aarch64-unknown-linux-gnu"

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "PKG_CONFIG_ALLOW_CROSS",
    "PKG_CONFIG_PATH",
]
